name: "Blog of Wharton"
description: "IT Tech. Blog by Wharon"

url: "http://wharton9.github.io/blog/"
loadingImg: "http://wharton9.github.io/blog/img/loading.gif"
filePath: "http://wharton9.github.io/blog/img/"

timezone: Asia/Shanghai

paginate: 16
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

gems:
- jekyll-paginate
- github-pages
